import { User, Heart, Briefcase } from 'lucide-react'

export const NAV_CATEGORIES = [
  {
    id: 'personal',
    title: 'Diri Pribadi',
    subtitle: 'Personal Growth',
    icon: User,
    theme: 'bg-white text-indigo-600 border-indigo-100',
    accent: 'text-indigo-500',
    gradient: 'from-indigo-500/20 to-indigo-700/20',
    items: [
      {
        problem: 'Luka Batin & Trauma Masa Lalu: Masihkah Mengganggu Hidupmu?',
        product: '',
        solution: {
          stages: [
            {
              title: 'Self-Assessment Awal',
              description: 'Mengidentifikasi ledakan emosi, rasa hampa, overthinking, dan pola luka masa lalu.',
            },
            {
              title: 'Analisis Psikologis',
              description: 'Psikolog membaca hasil asesmen dan memetakan akar trauma serta tingkat dampaknya.',
            },
            {
              title: 'Konsultasi Mendalam',
              description: 'Eksplorasi pengalaman masa lalu, relasi, dan emotional trigger utama.',
            },
            {
              title: 'Intervensi & Healing',
              description: 'Teknik pengelolaan emosi, inner child healing, dan pemrosesan trauma.',
            },
            {
              title: 'Pembentukan Pola Baru',
              description: 'Belajar respon sehat, membangun self-worth, dan hubungan yang lebih stabil.',
            },
            {
              title: 'Follow Up & Monitoring',
              description: 'Evaluasi progres dan penyesuaian strategi pemulihan.',
            },
          ],
        },
        benefit: {
          before: [
            'Emosi meledak tiba-tiba',
            'Merasa hampa tanpa alasan',
            'Terjebak masa lalu',
            'Overthinking berlebihan',
            'Sulit percaya orang lain',
            'Hubungan berulang menyakitkan',
          ],
          after: [
            'Emosi lebih stabil & terkendali',
            'Lebih tenang menghadapi trigger',
            'Berdamai dengan masa lalu',
            'Pikiran lebih jernih',
            'Lebih percaya diri',
            'Mampu membangun hubungan sehat',
          ],
        },
      },
      {
        problem: 'Anxiety, Depresi & Burnout Check: Kamu Capek Biasa atau Sudah Overload?',
        product: '',
        solution: {
          stages: [
            { title: 'Self-Assessment Awal', description: 'Mengukur tingkat kecemasan, gejala depresi, dan burnout akibat tekanan kerja & hidup.' },
            { title: 'Analisis Psikologis', description: 'Psikolog memetakan apakah yang dialami: lelah biasa, burnout, anxiety, atau depresi.' },
            { title: 'Konsultasi Mendalam', description: 'Menggali sumber tekanan: pekerjaan, relasi, beban mental, dan pola hidup.' },
            { title: 'Intervensi & Pemulihan', description: 'Teknik manajemen stres, regulasi emosi, pengaturan energi, dan coping strategy.' },
            { title: 'Penataan Pola Hidup & Kerja', description: 'Membentuk batas sehat, manajemen beban, dan keseimbangan mental.' },
            { title: 'Monitoring & Follow Up', description: 'Evaluasi progres dan penyesuaian strategi pemulihan.' },
          ],
        },
        benefit: {
          before: [
            'Merasa lelah terus-menerus',
            'Sulit fokus & mudah terdistraksi',
            'Overthinking & cemas berlebihan',
            'Kehilangan motivasi bekerja',
            'Mudah emosional & sensitif',
            'Merasa kewalahan dengan tugas',
          ],
          after: [
            'Energi mental lebih stabil',
            'Fokus & produktivitas meningkat',
            'Lebih tenang menghadapi tekanan',
            'Motivasi kerja kembali',
            'Emosi lebih terkendali',
            'Mampu mengatur beban dengan sehat',
          ],
        },
      },
      {
        problem: 'Citra Diri & Tingkat Pede Check : Kenapa Aku Nggak Pernah Merasa Dihargai',
        product: '',
        solution: {
          stages: [
            { title: 'Self-Assessment Citra Diri', description: 'Mengukur tingkat kepercayaan diri, self-image, dan kebutuhan validasi dari orang lain.' },
            { title: 'Analisis Psikologis', description: 'Psikolog mengidentifikasi pola perfeksionisme, self-doubt, dan standar diri yang terlalu tinggi.' },
            { title: 'Konsultasi Mendalam', description: 'Menggali pengalaman yang membentuk rasa tidak percaya diri dan kebutuhan akan pengakuan.' },
            { title: 'Intervensi Psikologis', description: 'Latihan membangun self-worth, mengurangi self-criticism, dan memperbaiki cara memandang diri.' },
            { title: 'Pembentukan Pola Pikir Baru', description: 'Mengembangkan kepercayaan diri internal dan kemampuan menghargai pencapaian diri.' },
            { title: 'Monitoring & Follow Up', description: 'Evaluasi perubahan citra diri dan peningkatan rasa percaya diri.' },
          ],
        },
        benefit: {
          before: [
            'Merasa tidak pernah cukup',
            'Kurang percaya diri',
            'Butuh validasi dari orang lain',
            'Takut dinilai atau gagal',
            'Sulit menghargai pencapaian diri',
            'Sering membandingkan diri dengan orang lain',
          ],
          after: [
            'Kepercayaan diri lebih kuat dari dalam',
            'Lebih menghargai diri sendiri',
            'Tidak bergantung pada validasi orang lain',
            'Lebih berani mengambil kesempatan',
            'Mampu mengakui pencapaian diri',
            'Citra diri lebih positif & sehat',
          ],
        },
      },
      {
        problem: 'Quarter-life Crisis & Perbandingan Sosial : Kenapa Aku Merasa Tertinggal?',
        product: '',
        solution: {
          stages: [
            { title: 'Self-Assessment Quarter-Life Crisis', description: 'Mengukur tingkat kecemasan terhadap pencapaian hidup dan kebiasaan membandingkan diri.' },
            { title: 'Analisis Psikologis', description: 'Psikolog mengidentifikasi tekanan sosial, ekspektasi diri, dan rasa tertinggal.' },
            { title: 'Konsultasi Mendalam', description: 'Menggali sumber kecemasan: karier, relasi, finansial, dan timeline hidup.' },
            { title: 'Intervensi Psikologis', description: 'Mengurangi social comparison, mengelola kecemasan masa depan, dan membangun self-acceptance.' },
            { title: 'Pemetaan Arah Hidup Pribadi', description: 'Menentukan tujuan realistis sesuai nilai dan kecepatan masing-masing.' },
            { title: 'Monitoring & Follow Up', description: 'Evaluasi progres dan penguatan mindset pertumbuhan pribadi.' },
          ],
        },
        benefit: {
          before: [
            'Merasa tertinggal dari orang lain',
            'Sering membandingkan pencapaian',
            'Cemas terhadap masa depan',
            'Bingung arah hidup',
            'Minder melihat kesuksesan orang lain',
            'Merasa hidup tidak berkembang',
          ],
          after: [
            'Lebih fokus pada progres pribadi',
            'Tidak mudah terpengaruh pencapaian orang lain',
            'Lebih tenang menghadapi masa depan',
            'Arah hidup lebih jelas',
            'Lebih percaya pada timing diri sendiri',
            'Merasa cukup dan berkembang sesuai jalur sendiri',
          ],
        },
      },
      {
        problem: 'Tes IQ, Bakat Minat & Perencanaan Karier',
        product: '',
        solution: {
          stages: [
            { title: 'Tes IQ & Kapasitas Kognitif', description: 'Mengukur kemampuan logika, analisis, verbal, dan problem solving.' },
            { title: 'Assessment Bakat & Minat', description: 'Mengidentifikasi bidang yang sesuai dengan ketertarikan dan potensi alami.' },
            { title: 'Analisis Kepribadian Karier', description: 'Psikolog memetakan gaya kerja, kekuatan, dan lingkungan kerja yang cocok.' },
            { title: 'Konsultasi Karier Mendalam', description: 'Membahas kondisi saat ini, kebingungan karier, dan kemungkinan jalur alternatif.' },
            { title: 'Pemetaan Arah Karier', description: 'Menentukan bidang karier yang paling selaras dengan IQ, minat, dan kepribadian.' },
            { title: 'Strategi & Action Plan Karier', description: 'Rekomendasi langkah konkret untuk berpindah jalur atau mengembangkan karier.' },
          ],
        },
        benefit: {
          before: [
            'Bingung menentukan karier',
            'Merasa salah jurusan / pekerjaan',
            'Tidak yakin dengan potensi diri',
            'Takut berpindah jalur karier',
            'Bekerja tanpa arah jelas',
            'Tidak tahu kekuatan utama diri',
          ],
          after: [
            'Arah karier lebih jelas & terarah',
            'Mengetahui potensi intelektual diri',
            'Memahami bidang yang paling cocok',
            'Lebih yakin mengambil keputusan karier',
            'Memiliki strategi pengembangan diri',
            'Melangkah dengan tujuan yang lebih pasti',
          ],
        },
      },
      {
        problem: 'Simulasi Lolos Test PNS, Management Trainee & Recruitment BUMN',
        product: '',
        solution: {
          stages: [
            { title: 'Simulasi Tes Rekrutmen', description: 'Mengerjakan tes kognitif, logika, dan kepribadian seperti seleksi CPNS/BUMN/MT.' },
            { title: 'Analisis Hasil Psikologis', description: 'Psikolog mengevaluasi kemampuan berpikir, pola kerja, dan kesiapan seleksi.' },
            { title: 'Identifikasi Kelemahan', description: 'Menentukan area yang perlu ditingkatkan: logika, fokus, kecepatan, atau konsistensi.' },
            { title: 'Konsultasi Strategi Lolos Tes', description: 'Pembahasan teknik menjawab, manajemen waktu, dan pendekatan psikotes.' },
            { title: 'Latihan Terarah & Penguatan Mental', description: 'Simulasi ulang dengan fokus pada peningkatan performa dan ketahanan mental.' },
            { title: 'Evaluasi & Monitoring Progres', description: 'Pengukuran perkembangan dan kesiapan menghadapi tes sebenarnya.' },
          ],
        },
        benefit: {
          before: [
            'Tidak tahu format tes rekrutmen',
            'Kurang percaya diri menghadapi seleksi',
            'Kesulitan mengerjakan soal logika',
            'Mudah panik saat tes',
            'Manajemen waktu buruk',
            'Tidak tahu kelemahan diri',
          ],
          after: [
            'Lebih siap menghadapi tes seleksi',
            'Memahami pola soal rekrutmen',
            'Kecepatan & akurasi meningkat',
            'Lebih percaya diri saat tes',
            'Manajemen waktu lebih baik',
            'Mengetahui strategi lolos seleksi',
          ],
        },
      },
    ],
  },
  {
    id: 'relationship',
    title: 'Relationship',
    subtitle: 'Pasangan & Keluarga',
    icon: Heart,
    theme: 'bg-white text-rose-500 border-rose-100',
    accent: 'text-rose-400',
    gradient: 'from-rose-400/20 to-rose-600/20',
    items: [
      {
        problem: 'Red Flag Pasangan Baru: Lanjut ke Nikah atau Jangan?',
        product: '',
        solution: {
          stages: [
            { title: 'Self-Assessment Hubungan', description: 'Mengidentifikasi kecocokan karakter, nilai hidup, dan pola komunikasi pasangan.' },
            { title: 'Analisis Psikologis', description: 'Psikolog memetakan potensi red flag, dinamika relasi, dan risiko konflik jangka panjang.' },
            { title: 'Evaluasi Pola Hubungan', description: 'Menggali cara menyelesaikan konflik, kebutuhan emosional, dan ekspektasi komitmen.' },
            { title: 'Konsultasi Mendalam', description: 'Membahas kecocokan visi hidup, batasan sehat, dan kesiapan menuju pernikahan.' },
            { title: 'Rekomendasi Keputusan Relasi', description: 'Arahan objektif: lanjut, perlu diperbaiki, atau perlu dipertimbangkan ulang.' },
            { title: 'Strategi Hubungan Sehat', description: 'Panduan komunikasi, boundary, dan langkah membangun relasi yang stabil.' },
          ],
        },
        benefit: {
          before: [
            'Ragu dengan hubungan yang dijalani',
            'Sulit melihat red flag pasangan',
            'Terbawa emosi saat mengambil keputusan',
            'Takut salah memilih pasangan',
            'Bingung lanjut atau berhenti',
            'Mengabaikan perbedaan penting',
          ],
          after: [
            'Lebih objektif melihat hubungan',
            'Menyadari red flag sejak awal',
            'Keputusan hubungan lebih matang',
            'Memahami kecocokan jangka panjang',
            'Komunikasi lebih sehat',
            'Lebih yakin melanjutkan atau mengakhiri hubungan',
          ],
        },
      },
      {
        problem: 'Rumah Tangga Terancam? Cek Potensi Konflik, Trauma & Tanda Bahaya',
        product: '',
        solution: {
          stages: [
            { title: 'Assessment Hubungan Pernikahan', description: 'Mengukur kualitas komunikasi, konflik berulang, dan kepuasan hubungan.' },
            { title: 'Analisis Psikologis Pasangan', description: 'Psikolog memetakan dinamika relasi, potensi konflik, dan risiko keretakan.' },
            { title: 'Identifikasi Akar Masalah', description: 'Menggali trauma masa lalu, kebutuhan emosional, dan pola pertengkaran.' },
            { title: 'Konsultasi Pasangan Mendalam', description: 'Membahas komunikasi, ekspektasi, dan perbedaan yang memicu konflik.' },
            { title: 'Strategi Perbaikan Hubungan', description: 'Teknik komunikasi sehat, resolusi konflik, dan penguatan koneksi emosional.' },
            { title: 'Monitoring & Follow Up', description: 'Evaluasi perkembangan hubungan dan pencegahan konflik berulang.' },
          ],
        },
        benefit: {
          before: [
            'Komunikasi sering buntu',
            'Pertengkaran berulang dengan masalah sama',
            'Emosi mudah memuncak',
            'Merasa tidak dipahami pasangan',
            'Hubungan terasa renggang',
            'Bingung memperbaiki keadaan',
          ],
          after: [
            'Komunikasi lebih terbuka & sehat',
            'Konflik lebih mudah diselesaikan',
            'Emosi lebih terkendali saat diskusi',
            'Lebih memahami kebutuhan pasangan',
            'Hubungan lebih hangat & stabil',
            'Fondasi rumah tangga lebih kuat',
          ],
        },
      },
      {
        problem: 'Nikah Tapi Sepi: Kenapa Hidup Bersama Tapi terasa Sendiri?',
        product: '',
        solution: {
          stages: [
            { title: 'Assessment Kedekatan Emosional', description: 'Mengukur tingkat koneksi emosional, komunikasi, dan kualitas kebersamaan.' },
            { title: 'Analisis Psikologis Hubungan', description: 'Psikolog memetakan penyebab hilangnya keintiman dan dinamika relasi.' },
            { title: 'Identifikasi Akar Masalah', description: 'Menggali rutinitas, konflik tidak selesai, dan kebutuhan emosional yang terabaikan.' },
            { title: 'Konsultasi Pasangan Mendalam', description: 'Membahas harapan, perasaan tersembunyi, dan hambatan komunikasi.' },
            { title: 'Strategi Membangun Koneksi Kembali', description: 'Teknik komunikasi emosional, quality time, dan penguatan kedekatan.' },
            { title: 'Monitoring & Follow Up', description: 'Evaluasi perkembangan dan menjaga koneksi tetap terbangun.' },
          ],
        },
        benefit: {
          before: [
            'Tinggal bersama tapi terasa jauh',
            'Komunikasi hanya soal rutinitas',
            'Merasa kesepian dalam pernikahan',
            'Kedekatan emosional menurun',
            'Hubungan terasa hambar',
            'Tidak merasa dipahami pasangan',
          ],
          after: [
            'Kedekatan emosional kembali terbangun',
            'Komunikasi lebih hangat & terbuka',
            'Merasa lebih terhubung dengan pasangan',
            'Quality time lebih bermakna',
            'Hubungan lebih intim & hangat',
            'Rumah terasa lebih nyaman secara emosional',
          ],
        },
      },
      {
        problem: 'Single, HTS & Takut Ditolak: Mau Begini Terus atau Lembaran Baru?',
        product: '',
        solution: {
          stages: [
            { title: 'Self-Assessment Pola Relasi', description: 'Mengukur ketakutan ditolak, pola HTS, dan hambatan membuka hubungan baru.' },
            { title: 'Analisis Psikologis', description: 'Psikolog mengidentifikasi luka relasi masa lalu, trust issue, dan pola menghindar.' },
            { title: 'Identifikasi Akar Hambatan', description: 'Menggali pengalaman patah hati, rasa tidak layak dicintai, dan fear of rejection.' },
            { title: 'Konsultasi Mendalam', description: 'Membahas kesiapan emosional, kebutuhan hubungan, dan batasan yang sehat.' },
            { title: 'Strategi Membuka Hubungan Sehat', description: 'Latihan membangun kepercayaan diri, komunikasi, dan keberanian memulai relasi.' },
            { title: 'Monitoring & Follow Up', description: 'Evaluasi perubahan pola relasi dan kesiapan membangun hubungan baru.' },
          ],
        },
        benefit: {
          before: [
            'Terjebak dalam HTS',
            'Takut memulai hubungan baru',
            'Sulit percaya orang lain',
            'Trauma patah hati sebelumnya',
            'Merasa tidak layak dicintai',
            'Menghindari komitmen',
          ],
          after: [
            'Lebih berani membuka hubungan baru',
            'Kepercayaan diri meningkat',
            'Lebih siap membangun komitmen',
            'Mampu menetapkan batasan sehat',
            'Tidak takut ditolak',
            'Hubungan lebih jelas & sehat',
          ],
        },
      },
    ],
  },
  {
    id: 'professional',
    title: 'Bisnis & Perusahaan',
    subtitle: 'Professional Path',
    icon: Briefcase,
    theme: 'bg-white text-amber-600 border-amber-100',
    accent: 'text-amber-500',
    gradient: 'from-amber-500/20 to-amber-700/20',
    items: [
      {
        problem: 'Test untuk Promosi dan Kenaikan Jabatan',
        product: '',
        solution: {
          stages: [
            { title: 'Assessment Kesiapan Kepemimpinan', description: 'Mengukur kemampuan leadership, pengambilan keputusan, dan tanggung jawab manajerial.' },
            { title: 'Tes Kompetensi Manajerial', description: 'Evaluasi problem solving, komunikasi, delegasi, dan strategic thinking.' },
            { title: 'Analisis Psikologis Kandidat', description: 'Psikolog memetakan gaya kepemimpinan, potensi, dan risiko saat promosi.' },
            { title: 'Simulasi Peran Kepemimpinan', description: 'Studi kasus untuk melihat respon kandidat sebagai leader.' },
            { title: 'Rekomendasi Promosi Objektif', description: 'Penilaian kelayakan promosi dan area pengembangan yang diperlukan.' },
            { title: 'Action Plan Pengembangan Leader', description: 'Panduan peningkatan kompetensi sebelum atau setelah promosi.' },
          ],
        },
        benefit: {
          before: [
            'Promosi hanya berdasarkan performa teknis',
            'Risiko salah memilih leader',
            'Kandidat belum siap memimpin tim',
            'Transisi jabatan kurang mulus',
            'Konflik tim setelah promosi',
            'Keputusan promosi kurang objektif',
          ],
          after: [
            'Promosi lebih objektif & terukur',
            'Leader siap menjalankan peran baru',
            'Transisi jabatan lebih mulus',
            'Risiko salah promosi berkurang',
            'Tim lebih stabil setelah promosi',
            'Performa organisasi lebih terjaga',
          ],
        },
      },
      {
        problem: 'Branch Manager Assessment',
        product: '',
        solution: {
          stages: [
            { title: 'Assessment Kompetensi Branch Manager', description: 'Mengukur kemampuan leadership, operasional, dan orientasi bisnis kandidat.' },
            { title: 'Simulasi Pengelolaan Cabang', description: 'Studi kasus terkait target profit, operasional, dan tantangan lapangan.' },
            { title: 'Analisis Psikologis & Gaya Kepemimpinan', description: 'Psikolog memetakan pola pengambilan keputusan dan kemampuan memimpin tim.' },
            { title: 'Evaluasi Kemampuan Bisnis & Finansial', description: 'Menilai business acumen, pengelolaan target, dan kontrol biaya.' },
            { title: 'Rekomendasi Kesiapan Kandidat', description: 'Penilaian kelayakan memimpin cabang serta risiko yang perlu diantisipasi.' },
            { title: 'Action Plan Pengembangan Branch Manager', description: 'Panduan peningkatan kompetensi untuk kesiapan memimpin cabang.' },
          ],
        },
        benefit: {
          before: [
            'Penunjukan Branch Manager kurang objektif',
            'Risiko performa cabang tidak stabil',
            'Kandidat belum siap memimpin unit bisnis',
            'Pengambilan keputusan kurang matang',
            'Target cabang sulit tercapai',
            'Standar operasional tidak konsisten',
          ],
          after: [
            'Pemilihan Branch Manager lebih terukur',
            'Pemimpin cabang siap secara mental & kompetensi',
            'Target profit lebih terarah',
            'Operasional cabang lebih stabil',
            'Keputusan bisnis lebih matang',
            'Standar perusahaan lebih konsisten di setiap cabang',
          ],
        },
      },
      {
        problem: 'Leadership Competency Assessment',
        product: '',
        solution: {
          stages: [
            { title: 'Assessment Kompetensi Kepemimpinan', description: 'Mengukur kemampuan leadership, visi strategis, dan pengambilan keputusan.' },
            { title: 'Evaluasi Gaya Kepemimpinan', description: 'Mengidentifikasi cara memimpin, memotivasi tim, dan menghadapi tekanan.' },
            { title: 'Analisis Psikologis Leader', description: 'Psikolog memetakan kekuatan, risiko, dan potensi pengembangan.' },
            { title: 'Simulasi Kasus Kepemimpinan', description: 'Studi kasus untuk menilai strategic thinking dan problem solving.' },
            { title: 'Pemetaan Kompetensi & Gap Analysis', description: 'Membandingkan kompetensi saat ini dengan standar leadership ideal.' },
            { title: 'Individual Development Plan (IDP)', description: 'Rekomendasi pengembangan untuk mencetak pemimpin yang adaptif dan tangguh.' },
          ],
        },
        benefit: {
          before: [
            'Kepemimpinan masih fokus operasional',
            'Visi strategis belum jelas',
            'Pengambilan keputusan kurang matang',
            'Tim kurang terinspirasi',
            'Pengembangan leader tidak terarah',
            'Sulit beradaptasi dengan perubahan',
          ],
          after: [
            'Kepemimpinan lebih strategis & visioner',
            'Pengambilan keputusan lebih kuat',
            'Tim lebih terarah & termotivasi',
            'Kekuatan & gap leadership lebih jelas',
            'Pengembangan leader lebih terstruktur',
            'Pemimpin lebih adaptif terhadap perubahan',
          ],
        },
      },
      {
        problem: 'MT & MDP Assessment',
        product: '',
        solution: {
          stages: [
            { title: 'Assessment Potensi MT/MDP', description: 'Mengukur learning agility, leadership potential, dan daya juang kandidat.' },
            { title: 'Tes Kognitif & Analitis', description: 'Evaluasi kemampuan berpikir logis, problem solving, dan adaptasi belajar.' },
            { title: 'Analisis Psikologis Kandidat', description: 'Psikolog memetakan karakter, motivasi, dan kesiapan pengembangan jangka panjang.' },
            { title: 'Simulasi Kasus Bisnis & Kepemimpinan', description: 'Studi kasus untuk melihat respon kandidat dalam situasi kompetitif.' },
            { title: 'Pemetaan High Potential Talent', description: 'Mengidentifikasi kandidat dengan potensi eksekutif masa depan.' },
            { title: 'Rekomendasi Seleksi & Development Plan', description: 'Penilaian kelayakan MT/MDP dan arah pengembangan talenta.' },
          ],
        },
        benefit: {
          before: [
            'Seleksi MT/MDP kurang terukur',
            'Sulit mengidentifikasi high potential talent',
            'Kandidat kuat akademik tapi lemah karakter',
            'Risiko salah memilih talenta masa depan',
            'Program pengembangan kurang tepat sasaran',
            'Potensi leadership belum terpetakan',
          ],
          after: [
            'Seleksi MT/MDP lebih objektif & ketat',
            'High potential talent lebih teridentifikasi',
            'Kandidat siap mengikuti program pengembangan',
            'Risiko salah pilih talenta berkurang',
            'Leadership pipeline lebih kuat',
            'Investasi pengembangan lebih tepat sasaran',
          ],
        },
      },
      {
        problem: 'Recruitment for Staff Level',
        product: '',
        solution: {
          stages: [
            { title: 'Assessment Kandidat Staff', description: 'Mengukur kesesuaian kemampuan teknis, ketelitian, dan kesiapan kerja operasional.' },
            { title: 'Tes Kognitif & Ketelitian', description: 'Evaluasi fokus, akurasi kerja, dan kemampuan mengikuti instruksi.' },
            { title: 'Analisis Psikologis Kandidat', description: 'Psikolog memetakan sikap kerja, integritas, dan konsistensi performa.' },
            { title: 'Evaluasi Kesesuaian Posisi', description: 'Menilai kecocokan kandidat dengan kebutuhan pekerjaan dan budaya kerja.' },
            { title: 'Rekomendasi Seleksi Kandidat', description: 'Penilaian kandidat yang paling sesuai untuk posisi staff.' },
            { title: 'Laporan & Shortlist Final', description: 'Ranking kandidat dan rekomendasi hiring yang objektif.' },
          ],
        },
        benefit: {
          before: [
            'Seleksi kandidat memakan waktu lama',
            'Risiko salah rekrutmen tinggi',
            'Kandidat kurang teliti dalam pekerjaan',
            'Turnover staff tinggi',
            'Produktivitas operasional tidak stabil',
            'Penilaian kandidat kurang objektif',
          ],
          after: [
            'Proses rekrutmen lebih cepat & efisien',
            'Kandidat lebih sesuai dengan kebutuhan',
            'Ketelitian kerja lebih terjamin',
            'Turnover staff lebih rendah',
            'Operasional lebih stabil & produktif',
            'Keputusan hiring lebih objektif',
          ],
        },
      },
      {
        problem: 'Recruitment for Eksekutif Level',
        product: '',
        solution: {
          stages: [
            { title: 'Executive Leadership Assessment', description: 'Mengukur visi strategis, gaya kepemimpinan, dan kematangan eksekutif.' },
            { title: 'In-Depth Interview Psikologis', description: 'Menggali nilai pribadi, prinsip kepemimpinan, dan alignment dengan organisasi.' },
            { title: 'Simulasi Strategis Bisnis', description: 'Studi kasus untuk melihat pengambilan keputusan di level direksi.' },
            { title: 'Analisis Dampak Kepemimpinan', description: 'Psikolog memetakan pengaruh kandidat terhadap budaya dan arah perusahaan.' },
            { title: 'Evaluasi Kesesuaian dengan Stakeholder', description: 'Menilai alignment visi, gaya komunikasi, dan pendekatan leadership.' },
            { title: 'Rekomendasi Executive Hiring', description: 'Laporan komprehensif dan keputusan seleksi yang objektif & strategis.' },
          ],
        },
        benefit: {
          before: [
            'Pemilihan eksekutif kurang objektif',
            'Risiko tidak selaras dengan visi perusahaan',
            'Dampak leadership sulit diprediksi',
            'Potensi konflik dengan stakeholder',
            'Salah memilih arah strategis perusahaan',
            'Budaya organisasi berisiko berubah negatif',
          ],
          after: [
            'Pemilihan eksekutif lebih strategis',
            'Visi pemimpin selaras dengan perusahaan',
            'Dampak kepemimpinan lebih terukur',
            'Keputusan direksi lebih matang',
            'Alignment dengan stakeholder lebih kuat',
            'Arah organisasi lebih stabil & berkelanjutan',
          ],
        },
      },
      {
        problem: 'Person, Organization & Cultural Fit',
        product: '',
        solution: {
          stages: [
            { title: 'Assessment Cultural Fit', description: 'Mengukur keselarasan nilai pribadi kandidat dengan budaya perusahaan.' },
            { title: 'Tes Gaya Kerja & Preferensi Lingkungan', description: 'Evaluasi kecenderungan kerja: kompetitif vs kolaboratif, struktur vs fleksibel.' },
            { title: 'Analisis Psikologis Kandidat', description: 'Psikolog memetakan karakter kerja, motivasi, dan kebutuhan lingkungan kerja.' },
            { title: 'Pemetaan Kesesuaian dengan Budaya Perusahaan', description: 'Membandingkan profil kandidat dengan nilai dan budaya organisasi.' },
            { title: 'Evaluasi Risiko Ketidaksesuaian', description: 'Mengidentifikasi potensi konflik budaya dan risiko turnover.' },
            { title: 'Rekomendasi Cultural Fit Hiring', description: 'Laporan kesesuaian kandidat dan saran penempatan terbaik.' },
          ],
        },
        benefit: {
          before: [
            'Karyawan cepat resign karena tidak cocok',
            'Konflik budaya dalam tim',
            'Adaptasi kerja berjalan lambat',
            'Produktivitas tim tidak stabil',
            'Turnover karyawan tinggi',
            'Hiring hanya berdasarkan skill teknis',
          ],
          after: [
            'Karyawan lebih cocok dengan budaya kerja',
            'Retensi karyawan meningkat',
            'Tim lebih harmonis & kolaboratif',
            'Adaptasi kerja lebih cepat',
            'Turnover lebih rendah',
            'Hiring lebih tepat & strategis',
          ],
        },
      },
      {
        problem: 'Customized Competency Based Assessment',
        product: '',
        solution: {
          stages: [
            { title: 'Needs Analysis Organisasi', description: 'Mengidentifikasi kebutuhan kompetensi sesuai industri dan posisi.' },
            { title: 'Penyusunan Kamus Kompetensi', description: 'Menentukan indikator perilaku dan standar kompetensi perusahaan.' },
            { title: 'Desain Alat Ukur Customized', description: 'Psikolog merancang tes, simulasi, dan studi kasus yang relevan.' },
            { title: 'Pelaksanaan Assessment', description: 'Kandidat mengikuti asesmen sesuai kompetensi yang dibutuhkan.' },
            { title: 'Analisis Kompetensi & Gap', description: 'Membandingkan kemampuan kandidat dengan standar perusahaan.' },
            { title: 'Laporan & Rekomendasi Strategis', description: 'Hasil asesmen disertai rekomendasi seleksi atau pengembangan.' },
          ],
        },
        benefit: {
          before: [
            'Menggunakan tes standar yang kurang relevan',
            'Kompetensi spesifik tidak terukur',
            'Risiko salah memilih kandidat',
            'Hasil asesmen kurang aplikatif',
            'Standar kompetensi tidak jelas',
            'Keputusan HR kurang berbasis data',
          ],
          after: [
            'Asesmen sesuai kebutuhan perusahaan',
            'Kompetensi spesifik terukur jelas',
            'Seleksi kandidat lebih akurat',
            'Hasil lebih relevan & aplikatif',
            'Standar kompetensi lebih terstruktur',
            'Keputusan HR lebih objektif & strategis',
          ],
        },
      },
      {
        problem: 'Organization Audit based on 75 Mckinsey',
        product: '',
        solution: {
          stages: [
            { title: 'Assessment Awal Organisasi (7S McKinsey)', description: 'Mengukur Strategy, Structure, Systems, Shared Values, Style, Staff, dan Skills.' },
            { title: 'Pengumpulan Data & Diagnostik', description: 'Melalui survey, interview, dan review dokumen organisasi.' },
            { title: 'Analisis Keterkaitan 7 Elemen', description: 'Mengidentifikasi elemen yang selaras maupun yang saling menghambat.' },
            { title: 'Identifikasi Gap Organisasi', description: 'Menemukan ketidaksesuaian antara strategi, struktur, sistem, dan SDM.' },
            { title: 'Rekomendasi Perbaikan Terintegrasi', description: 'Strategi perbaikan organisasi secara menyeluruh dan terarah.' },
            { title: 'Roadmap Implementasi & Monitoring', description: 'Panduan eksekusi perubahan dan evaluasi perkembangan organisasi.' },
          ],
        },
        benefit: {
          before: [
            'Strategi dan struktur tidak selaras',
            'Sistem kerja menghambat performa',
            'Koordinasi antar tim kurang efektif',
            'Budaya organisasi tidak jelas',
            'Peran SDM tidak optimal',
            'Performa organisasi tidak maksimal',
          ],
          after: [
            'Seluruh elemen organisasi lebih selaras',
            'Struktur mendukung strategi bisnis',
            'Sistem kerja lebih efektif & efisien',
            'Budaya organisasi lebih kuat',
            'Penempatan SDM lebih tepat',
            'Performa organisasi lebih terintegrasi & optimal',
          ],
        },
      },
      {
        problem: 'Digital Transformation & Argentina AI Readiness Audit',
        product: '',
        solution: {
          stages: [
            { title: 'Assessment Kesiapan Transformasi Digital', description: 'Mengukur kesiapan organisasi dalam mengadopsi teknologi digital & AI.' },
            { title: 'Evaluasi Mindset & Budaya SDM', description: 'Menilai keterbukaan terhadap perubahan, inovasi, dan penggunaan AI.' },
            { title: 'Analisis Proses Bisnis', description: 'Mengidentifikasi proses yang dapat diotomasi atau dioptimalkan dengan AI.' },
            { title: 'Audit Infrastruktur & Sistem Kerja', description: 'Mengevaluasi kesiapan teknologi dan alur kerja pendukung.' },
            { title: 'Gap Analysis AI Readiness', description: 'Membandingkan kondisi saat ini dengan standar kesiapan transformasi digital.' },
            { title: 'Roadmap Transformasi & Implementasi', description: 'Rekomendasi strategi adopsi AI secara bertahap dan terintegrasi.' },
          ],
        },
        benefit: {
          before: [
            'Tim belum siap menghadapi transformasi digital',
            'Resistensi terhadap penggunaan AI',
            'Proses kerja masih manual & tidak efisien',
            'Investasi teknologi tidak optimal',
            'Budaya inovasi belum terbentuk',
            'Arah transformasi digital tidak jelas',
          ],
          after: [
            'Organisasi siap mengadopsi AI',
            'Mindset tim lebih terbuka terhadap teknologi',
            'Proses bisnis lebih otomatis & efisien',
            'Investasi teknologi lebih optimal',
            'Budaya inovasi lebih kuat',
            'Transformasi digital lebih terarah & terukur',
          ],
        },
      },
    ],
  },
]
