import {
  Heart, Zap, User, Compass, Brain, Building2
} from 'lucide-react'
import type { DiriPribadiProduct, TierPricing } from '../types'

const STANDARD_PERSONAL_PRICING: TierPricing[] = [
  {
    tier: 'dasar',
    label: 'Dasar',
    price: 30000,
    priceLabel: 'Rp 30.000',
    coverage: 'Menjelaskan ~70% pola utama',
  },
  {
    tier: 'lengkap',
    label: 'Lengkap',
    price: 85000,
    priceLabel: 'Rp 85.000',
    coverage: 'Sesuai kaidah konseptual & ilmiah',
  },
  {
    tier: 'comprehensive',
    label: 'Comprehensive',
    price: 300000,
    priceLabel: 'Rp 300.000',
    coverage: 'End-to-end, semua korelasi tertelusur',
  },
]

export const DIRI_PRIBADI_PRODUCTS: DiriPribadiProduct[] = [
  {
    id: 'dp-trauma-luka-batin',
    slug: 'luka-batin-trauma',
    title: 'Luka Batin & Trauma Masa Lalu',
    subtitle: 'Masihkah Mengganggu Hidupmu?',
    painPoint: 'Pernah merasa "meledak" tiba-tiba atau merasa hampa tanpa alasan yang jelas?',
    description: 'Seringkali, reaksi kita hari ini adalah gema dari luka yang belum sembuh di masa lalu. Asesmen ini membantu kamu mengidentifikasi trauma masa kecil atau pengalaman pahit yang masih membekas secara tidak sadar. Dengan mengenali akarnya, kamu bisa mulai berdamai dengan diri sendiri dan berhenti membiarkan masa lalu mendikte masa depanmu.',
    icon: Heart,
    category: 'diri-pribadi',
    users: '8k+',
    duration: '30-60 Menit',
    pricing: STANDARD_PERSONAL_PRICING,
  },
  {
    id: 'dp-anxiety-burnout',
    slug: 'anxiety-depresi-burnout',
    title: 'Anxiety, Depresi & Burnout Check',
    subtitle: 'Kamu Error, Capek Biasa atau Sudah Overload?',
    painPoint: 'Di dunia yang serba cepat ini, batas antara "lelah bekerja" dan "lelah mental" seringkali kabur.',
    description: 'Apakah kamu hanya butuh tidur di akhir pekan, atau mentalmu memang sedang meminta pertolongan? Asesmen ini dirancang untuk mendeteksi tingkat kecemasan, gejala depresi, dan kelelahan mental (burnout) secara akurat. Jangan tunggu sampai mesinmu benar-benar mati.',
    icon: Zap,
    category: 'diri-pribadi',
    users: '12k+',
    duration: '20-45 Menit',
    pricing: STANDARD_PERSONAL_PRICING,
  },
  {
    id: 'dp-citra-diri-pede',
    slug: 'citra-diri-self-worth',
    title: 'Citra Diri & Tingkat PeDe Check',
    subtitle: 'Kenapa Aku Nggak Pernah Merasa Berharga dan Exist?',
    painPoint: 'Apakah kamu merasa sudah melakukan segalanya tapi tetap merasa "kurang"?',
    description: 'Kurangnya rasa percaya diri seringkali berakar dari cara kita memandang diri sendiri atau self-image. Program ini membantu kamu membedah standar tinggi yang kamu buat sendiri dan memahami mengapa validasi orang lain terasa begitu penting. Temukan kembali harga dirimu dan bangun kepercayaan diri dari dalam.',
    icon: User,
    category: 'diri-pribadi',
    users: '9k+',
    duration: '25-50 Menit',
    pricing: STANDARD_PERSONAL_PRICING,
  },
  {
    id: 'dp-quarter-life-crisis',
    slug: 'quarter-life-crisis-perbandingan-sosial',
    title: 'Quarter-Life Crisis & Perbandingan Sosial',
    subtitle: 'Kenapa Aku Merasa Tertinggal?',
    painPoint: 'Melihat teman di media sosial sudah sukses, menikah, atau keliling dunia seringkali membuat kita merasa "kalah start".',
    description: 'Fenomena Quarter-Life Crisis ini nyata dan sangat melelahkan. Asesmen ini membantu kamu memproses rasa cemas akibat perbandingan sosial dan memetakan kembali jalur hidupmu sendiri. Berhentilah menggunakan standar orang lain untuk mengukur kebahagiaanmu.',
    icon: Compass,
    category: 'diri-pribadi',
    users: '15k+',
    duration: '30 Menit',
    pricing: STANDARD_PERSONAL_PRICING,
  },
  {
    id: 'dp-iq-bakat-karir',
    slug: 'tes-iq-bakat-perencanaan-karir',
    title: 'Tes IQ, Bakat Minat & Perencanaan Karier',
    subtitle: '',
    painPoint: 'Memilih karier bukan cuma soal gaji, tapi soal keselarasan antara potensi otak dan minat hati.',
    description: 'Melalui tes komprehensif ini, kamu akan mendapatkan gambaran jelas mengenai kapasitas kognitif (IQ) serta bidang yang paling cocok dengan kepribadianmu. Sangat cocok untuk mahasiswa atau profesional yang merasa salah jurusan atau ingin berpindah haluan.',
    icon: Brain,
    category: 'diri-pribadi',
    users: '20k+',
    duration: '45-90 Menit',
    pricing: STANDARD_PERSONAL_PRICING,
  },
  {
    id: 'dp-simulasi-cpns-mt-bumn',
    slug: 'simulasi-pns-mt-bumn',
    title: 'Simulasi Lolos Test PNS, Management Trainee & Recruitment BUMN',
    subtitle: '',
    painPoint: 'Persaingan di dunia kerja, terutama untuk posisi prestisius seperti BUMN atau CPNS, sangatlah ketat.',
    description: 'Asesmen ini memberikan simulasi nyata yang mencakup tes kognitif, kepribadian, hingga logic test yang sering digunakan perusahaan besar. Kamu tidak hanya sekadar mengerjakan soal, tapi juga mendapatkan evaluasi mendalam tentang titik lemahmu.',
    icon: Building2,
    category: 'diri-pribadi',
    users: '25k+',
    duration: '60-100 Menit',
    pricing: STANDARD_PERSONAL_PRICING,
  },
]
