import { AlertTriangle, Home, HeartCrack, UserX } from 'lucide-react'
import type { RelationshipProduct, TierPricing } from '../types'

const STANDARD_RELATIONSHIP_PRICING: TierPricing[] = [
  {
    tier: 'dasar',
    label: 'Dasar',
    price: 30000,
    priceLabel: 'Rp 30.000',
    coverage: 'Menjelaskan ~70% pola utama relasi',
  },
  {
    tier: 'lengkap',
    label: 'Lengkap',
    price: 85000,
    priceLabel: 'Rp 85.000',
    coverage: 'Sesuai kaidah konseptual & ilmiah',
  },
  {
    tier: 'comprehensive',
    label: 'Comprehensive',
    price: 300000,
    priceLabel: 'Rp 300.000',
    coverage: 'End-to-end, semua korelasi tertelusur',
  },
]

export const RELATIONSHIP_PRODUCTS: RelationshipProduct[] = [
  {
    id: 'rel-red-flag-pasangan-baru',
    slug: 'red-flag-pasangan-baru',
    title: 'Red Flag Pasangan Baru',
    subtitle: 'Lanjut ke Nikah atau Jangan?',
    painPoint: 'Jatuh cinta memang indah, tapi jangan sampai membutakan kita dari tanda-tanda bahaya.',
    description: 'Sebelum memutuskan untuk berkomitmen lebih jauh, penting untuk mengenali pola perilaku pasangan yang berpotensi merugikan di masa depan. Asesmen ini membantumu melihat secara objektif kecocokan karakter, nilai hidup, dan cara berkomunikasi pasangan.',
    icon: AlertTriangle,
    category: 'relationship',
    canDoWithPartner: true,
    subIssues: [
      { id: 'kecocokan-nilai', label: 'Kecocokan Nilai & Karakter', shortDesc: 'Apakah nilai hidup kalian selaras?' },
      { id: 'pola-komunikasi', label: 'Pola Komunikasi Awal', shortDesc: 'Bagaimana gaya komunikasi pasangan?' },
      { id: 'red-flag-behavior', label: 'Deteksi Red Flag Perilaku', shortDesc: 'Ada tanda-tanda bahaya yang perlu diwaspadai?' },
      { id: 'kesiapan-komitmen', label: 'Kesiapan Komitmen & Nikah', shortDesc: 'Seberapa siap masing-masing untuk berkomitmen?' },
    ],
    pricing: STANDARD_RELATIONSHIP_PRICING,
    users: '5k+',
    duration: '30-50 Menit',
  },
  {
    id: 'rel-konflik-trauma-rumah-tangga',
    slug: 'konflik-trauma-rumah-tangga',
    title: 'Rumah Tangga Terancam?',
    subtitle: 'Cek Potensi Konflik, Trauma & Tanda Bahaya',
    painPoint: 'Setiap pernikahan pasti punya badai, tapi apakah badaimu kali ini bisa dilewati?',
    description: 'Asesmen ini dirancang untuk pasangan yang merasa komunikasinya mulai macet atau sering terjebak dalam pertengkaran yang sama berulang kali. Kami membantu memetakan potensi konflik, pengaruh trauma masa lalu, serta mendeteksi tanda bahaya yang perlu segera ditangani.',
    icon: Home,
    category: 'relationship',
    canDoWithPartner: true,
    subIssues: [
      { id: 'perselingkuhan', label: 'Pasangan Selingkuh', shortDesc: 'Deteksi dan pemulihan pasca perselingkuhan' },
      { id: 'kekerasan-verbal', label: 'Diremehkan, Direndahkan, Dihinakan', shortDesc: 'Apakah ini emotional abuse?' },
      { id: 'kdrt', label: 'KDRT', shortDesc: 'Kenali tanda-tanda dan langkah perlindungan diri' },
      { id: 'npd-psikopat', label: 'Kecenderungan NPD & Psikopat', shortDesc: 'Apakah pasanganmu memiliki gangguan kepribadian?' },
      { id: 'konflik-rumah-tangga', label: 'Konflik Pola Asuh, Keuangan & Seksual', shortDesc: 'Ketegangan akibat pembagian tugas dan perbedaan kebutuhan' },
      { id: 'ldr', label: 'LDR', shortDesc: 'Mengelola hubungan jarak jauh dengan sehat' },
      { id: 'tekanan-komitmen', label: 'The Biological Clock & Tekanan Komitmen', shortDesc: 'Konflik soal anak, karir, dan penghasilan' },
    ],
    pricing: STANDARD_RELATIONSHIP_PRICING,
    users: '3k+',
    duration: '40-60 Menit',
  },
  {
    id: 'rel-nikah-sepi',
    slug: 'nikah-tapi-sepi',
    title: 'Nikah Tapi Sepi',
    subtitle: 'Kenapa Hidup Bersama, Tapi Terasa Sendiri?',
    painPoint: 'Berbagi tempat tidur tapi tidak berbagi perasaan adalah bentuk kesepian yang paling menyesakkan.',
    description: 'Fenomena "lonely together" sering terjadi saat keintiman emosional mulai memudar akibat rutinitas atau masalah yang tidak terselesaikan. Program ini membantu pasangan untuk kembali saling "melihat" dan "mendengar". Temukan penyebab hilangnya koneksi dan pelajari cara membangun kembali jembatan emosional.',
    icon: HeartCrack,
    category: 'relationship',
    canDoWithPartner: true,
    subIssues: [
      { id: 'kehilangan-koneksi', label: 'Kehilangan Koneksi Emosional', shortDesc: 'Sudah lama tidak benar-benar "terhubung"' },
      { id: 'rutinitas-membosankan', label: 'Rutinitas & Kejenuhan Kronis', shortDesc: 'Pernikahan terasa autopilot dan hampa' },
      { id: 'ldr-kesendirian', label: 'LDR & Kesepian Fisik', shortDesc: 'Terpisah jarak, merasa semakin asing' },
      { id: 'memendam-emosi', label: 'Memendam Emosi demi Keluarga', shortDesc: 'Mengorbankan diri sendiri untuk menjaga keutuhan' },
    ],
    pricing: STANDARD_RELATIONSHIP_PRICING,
    users: '4k+',
    duration: '35-55 Menit',
  },
  {
    id: 'rel-single-tidak-happy',
    slug: 'single-hts-takut-ditolak',
    title: 'Single, HTS & Takut Ditolak',
    subtitle: 'Mau Begini Terus, atau Lembaran Baru?',
    painPoint: 'Terjebak dalam Hubungan Tanpa Status (HTS) atau terlalu lama melajang karena takut patah hati lagi?',
    description: 'Ketakutan akan penolakan seringkali membuat kita membangun benteng yang terlalu tinggi. Asesmen ini membantu kamu memahami pola relasimu dan mengatasi hambatan emosional yang menghalangimu untuk membuka hati secara sehat.',
    icon: UserX,
    category: 'relationship',
    canDoWithPartner: false,
    subIssues: [
      { id: 'anxiety-lawan-jenis', label: 'Anxiety dengan Lawan Jenis & Lingkungan', shortDesc: 'Takut ditolak, sulit pasang boundaries' },
      { id: 'body-image-single', label: 'Body Image & Self-Worth', shortDesc: 'Tidak PeDe atas penampilan dan diri sendiri' },
      { id: 'hts-ketidakpastian', label: 'Situasi Gak Jelas & HTS', shortDesc: 'Mau lanjut atau tidak? Bingung membedakan rasa' },
    ],
    pricing: STANDARD_RELATIONSHIP_PRICING,
    users: '7k+',
    duration: '25-45 Menit',
  },
]
