import {
  Heart, Crown, Flame, Link2, Brain, Compass,
  MessageCircleHeart, Shield, Handshake, Clock,
} from 'lucide-react'
import type { RelationshipProduct, TierPricing } from '../types'

const STANDARD_RELATIONSHIP_PRICING: TierPricing[] = [
  {
    tier: 'dasar',
    label: 'Dasar',
    price: 30000,
    priceLabel: 'Rp 30.000',
    coverage: 'Menjelaskan ~70% pola utama relasi',
  },
  {
    tier: 'lengkap',
    label: 'Lengkap',
    price: 85000,
    priceLabel: 'Rp 85.000',
    coverage: 'Sesuai kaidah konseptual & ilmiah',
  },
  {
    tier: 'comprehensive',
    label: 'Comprehensive',
    price: 300000,
    priceLabel: 'Rp 300.000',
    coverage: 'End-to-end, semua korelasi tertelusur',
  },
]

export const RELATIONSHIP_PRODUCTS: RelationshipProduct[] = [
  {
    id: 'rel-kepribadian-narcistic',
    slug: 'kepribadian-narcistic',
    title: 'Kepribadian Narcistic',
    subtitle: 'Seberapa Narsis Dirimu atau Pasanganmu?',
    painPoint: 'Narsisme yang tidak disadari bisa merusak hubungan dari dalam — kenali sebelum terlambat.',
    description: 'Mengukur tingkat sifat narsistik pada individu menggunakan NPI (Narcissistic Personality Inventory). Asesmen ini mengidentifikasi pola grandiosity, entitlement, exhibitionism, exploitativeness, authority, self-sufficiency, superiority, dan vanity.',
    icon: Crown,
    category: 'relationship',
    canDoWithPartner: true,
    subIssues: [
      { id: 'grandiosity', label: 'Grandiosity', shortDesc: 'Perasaan diri istimewa, unik, atau lebih hebat dari orang lain' },
      { id: 'entitlement', label: 'Entitlement', shortDesc: 'Merasa berhak mendapat perlakuan khusus' },
      { id: 'exhibitionism', label: 'Exhibitionism', shortDesc: 'Kebutuhan menjadi pusat perhatian' },
      { id: 'exploitativeness', label: 'Exploitativeness', shortDesc: 'Kecenderungan memanfaatkan orang lain' },
      { id: 'authority', label: 'Authority', shortDesc: 'Kecenderungan menguasai dan memimpin' },
      { id: 'self-sufficiency', label: 'Self-Sufficiency', shortDesc: 'Keyakinan mampu mandiri tanpa bantuan' },
      { id: 'superiority', label: 'Superiority', shortDesc: 'Merasa lebih unggul dibanding orang lain' },
      { id: 'vanity', label: 'Vanity', shortDesc: 'Kecenderungan terlalu memperhatikan penampilan' },
    ],
    pricing: STANDARD_RELATIONSHIP_PRICING,
    users: '5k+',
    duration: '20-35 Menit',
  },
  {
    id: 'rel-sex-life',
    slug: 'sex-life',
    title: 'Sex Life',
    subtitle: 'Pahami Preferensi & Sikap Seksualmu',
    painPoint: 'Ketidakcocokan seksual yang tidak dibicarakan sering menjadi sumber konflik tersembunyi dalam hubungan.',
    description: 'Mengukur sikap dan preferensi seseorang terhadap seksualitas menggunakan Kink Aware Questionnaire, termasuk pemahaman terhadap praktik kink/BDSM dan seksualitas non-normatif.',
    icon: Flame,
    category: 'relationship',
    canDoWithPartner: true,
    subIssues: [
      { id: 'knowledge-awareness', label: 'Knowledge & Awareness', shortDesc: 'Pengetahuan faktual tentang kink/seksualitas' },
      { id: 'attitudes-toward-kink', label: 'Attitudes toward Kink', shortDesc: 'Sikap personal terhadap seksualitas non-normatif' },
      { id: 'pathology-beliefs', label: 'Pathology & Beliefs', shortDesc: 'Keyakinan medis terkait gangguan seksualitas' },
      { id: 'clinical-comfort', label: 'Clinical/Professional Comfort', shortDesc: 'Tingkat kenyamanan profesional' },
      { id: 'professional-competence', label: 'Professional Competence & Ethics', shortDesc: 'Kompetensi dan etika profesional' },
    ],
    pricing: STANDARD_RELATIONSHIP_PRICING,
    users: '3k+',
    duration: '25-40 Menit',
  },
  {
    id: 'rel-sociosexual-orientation',
    slug: 'sociosexual-orientation',
    title: 'Sociosexual Orientation',
    subtitle: 'Kasual atau Komitmen?',
    painPoint: 'Perbedaan orientasi seksual-sosial yang tidak disadari bisa menjadi akar ketidakcocokan dalam hubungan.',
    description: 'Mengukur kecenderungan individu terhadap seks kasual versus seks yang didasari komitmen menggunakan SOI-R (Sociosexual Orientation Inventory).',
    icon: Compass,
    category: 'relationship',
    canDoWithPartner: true,
    subIssues: [
      { id: 'sociosexual-behavior', label: 'Sociosexual Behavior', shortDesc: 'Perilaku seksual tanpa komitmen' },
      { id: 'sociosexual-attitude', label: 'Sociosexual Attitude', shortDesc: 'Sikap terhadap seks di luar hubungan serius' },
      { id: 'sociosexual-desire', label: 'Sociosexual Desire', shortDesc: 'Fantasi dan gairah terhadap orang yang bukan pasangan tetap' },
    ],
    pricing: STANDARD_RELATIONSHIP_PRICING,
    users: '4k+',
    duration: '15-25 Menit',
  },
  {
    id: 'rel-attachment-style',
    slug: 'attachment-style',
    title: 'Attachment Style',
    subtitle: 'Bagaimana Gaya Kelekatan dalam Hubunganmu?',
    painPoint: 'Gaya kelekatan yang tidak sehat bisa membuat hubungan terasa menyiksa — baik terlalu lengket maupun terlalu menjauh.',
    description: 'Mengukur gaya kelekatan (attachment style) pada orang dewasa menggunakan ECR-R (Experiences in Close Relationships-Revised) dan Adult Attachment Scale (AAS). Identifikasi pola hubunganmu: secure, anxious, atau avoidant.',
    icon: Link2,
    category: 'relationship',
    canDoWithPartner: true,
    subIssues: [
      { id: 'attachment-anxiety', label: 'Attachment Anxiety', shortDesc: 'Kecemasan berlebih akan ditinggalkan' },
      { id: 'attachment-avoidance', label: 'Attachment Avoidance', shortDesc: 'Kecenderungan menghindari kedekatan emosional' },
      { id: 'secure', label: 'Secure', shortDesc: 'Rasa nyaman, percaya, dan terbuka' },
      { id: 'anxious', label: 'Anxious', shortDesc: 'Takut kehilangan, cemburu, dan bergantung' },
      { id: 'avoidant', label: 'Avoidant', shortDesc: 'Suka menyendiri, takut komitmen' },
    ],
    pricing: STANDARD_RELATIONSHIP_PRICING,
    users: '8k+',
    duration: '25-40 Menit',
  },
  {
    id: 'rel-maturity-profile',
    slug: 'maturity-profile',
    title: 'Maturity Profile',
    subtitle: 'Seberapa Matang Emosi & Relasimu?',
    painPoint: 'Ketidakmatangan emosional adalah penyebab utama konflik berulang yang tidak pernah terselesaikan.',
    description: 'Mengukur tingkat kematangan emosional seseorang menggunakan Emotional Maturity Scale. Asesmen ini menilai kemampuan mengelola emosi secara sehat dalam konteks hubungan dan kehidupan sosial.',
    icon: Brain,
    category: 'relationship',
    canDoWithPartner: true,
    subIssues: [
      { id: 'emotional-stability', label: 'Emotional Stability', shortDesc: 'Kemampuan menjaga ketenangan di bawah tekanan' },
      { id: 'emotional-progression', label: 'Emotional Progression', shortDesc: 'Kemampuan bertumbuh dan belajar dari pengalaman' },
      { id: 'social-adjustment', label: 'Social Adjustment', shortDesc: 'Kemampuan menyesuaikan diri dalam kehidupan sosial' },
      { id: 'personality-integration', label: 'Personality Integration', shortDesc: 'Keselarasan antara emosional dan kepribadian' },
      { id: 'independence', label: 'Independence', shortDesc: 'Kemandirian emosional dan pengambilan keputusan' },
    ],
    pricing: STANDARD_RELATIONSHIP_PRICING,
    users: '6k+',
    duration: '30-45 Menit',
  },
  {
    id: 'rel-value-attitude-trust',
    slug: 'value-attitude-trust',
    title: 'Value, Attitude & Trust',
    subtitle: 'Apa Nilai Hidup yang Kamu Pegang Teguh?',
    painPoint: 'Perbedaan nilai dasar yang tidak teridentifikasi bisa menjadi bom waktu dalam hubungan jangka panjang.',
    description: 'Mengukur nilai-nilai dasar (human values) yang menjadi pedoman hidup seseorang menggunakan Schwartz Value Survey (SVS). Pahami apakah nilai hidupmu dan pasangan benar-benar selaras.',
    icon: Shield,
    category: 'relationship',
    canDoWithPartner: true,
    subIssues: [
      { id: 'openness-to-change', label: 'Openness to Change', shortDesc: 'Keterbukaan terhadap perubahan dan hal baru' },
      { id: 'conservation', label: 'Conservation', shortDesc: 'Kecenderungan menjaga tradisi dan stabilitas' },
      { id: 'hedonism', label: 'Hedonism', shortDesc: 'Orientasi pada kesenangan dan kenikmatan hidup' },
      { id: 'self-enhancement', label: 'Self-Enhancement', shortDesc: 'Dorongan untuk pencapaian dan kekuasaan' },
      { id: 'self-transcendence', label: 'Self-Transcendence', shortDesc: 'Kepedulian terhadap kesejahteraan orang lain' },
    ],
    pricing: STANDARD_RELATIONSHIP_PRICING,
    users: '4k+',
    duration: '25-40 Menit',
  },
  {
    id: 'rel-5-love-language',
    slug: '5-love-language',
    title: '5 Love Language',
    subtitle: 'Bagaimana Caramu Memberi & Menerima Cinta?',
    painPoint: 'Banyak pasangan merasa tidak dicintai bukan karena kurang cinta, tapi karena "bahasa cinta" yang berbeda.',
    description: 'Mengidentifikasi cara utama seseorang memberi dan menerima kasih sayang dalam hubungan interpersonal menggunakan The Five Love Languages (Gary Chapman).',
    icon: MessageCircleHeart,
    category: 'relationship',
    canDoWithPartner: true,
    subIssues: [
      { id: 'words-of-affirmation', label: 'Words of Affirmation', shortDesc: 'Ekspresi cinta melalui kata-kata pujian dan dukungan' },
      { id: 'quality-time', label: 'Quality Time', shortDesc: 'Cinta melalui kehadiran dan waktu berkualitas' },
      { id: 'acts-of-service', label: 'Acts of Service', shortDesc: 'Cinta melalui tindakan nyata dan bantuan' },
      { id: 'receiving-gifts', label: 'Receiving Gifts', shortDesc: 'Cinta melalui pemberian hadiah bermakna' },
      { id: 'physical-touch', label: 'Physical Touch', shortDesc: 'Cinta melalui sentuhan fisik dan kedekatan' },
    ],
    pricing: STANDARD_RELATIONSHIP_PRICING,
    users: '12k+',
    duration: '15-25 Menit',
  },
  {
    id: 'rel-dominance-pride-power',
    slug: 'dominance-pride-power',
    title: 'Tes Dominance, Pride & Power',
    subtitle: 'Siapa yang Mendominasi dalam Hubunganmu?',
    painPoint: 'Ketimpangan kekuasaan dalam hubungan sering tidak disadari, tapi dampaknya sangat merusak.',
    description: 'Mengukur sejauh mana seseorang mendukung hierarki sosial dan kecenderungan dominasi menggunakan Social Dominance Orientation (SDO). Pahami pola kekuasaan dalam hubunganmu.',
    icon: Crown,
    category: 'relationship',
    canDoWithPartner: true,
    subIssues: [
      { id: 'sdo-dominance', label: 'SDO-Dominance', shortDesc: 'Kecenderungan mendukung hierarki dan dominasi kelompok' },
      { id: 'sdo-egalitarianism', label: 'SDO-Egalitarianism', shortDesc: 'Sikap terhadap kesetaraan sosial dan keadilan' },
    ],
    pricing: STANDARD_RELATIONSHIP_PRICING,
    users: '3k+',
    duration: '15-25 Menit',
  },
  {
    id: 'rel-interpersonal-power',
    slug: 'interpersonal-power',
    title: 'Interpersonal Power',
    subtitle: 'Bagaimana Dinamika Kekuasaan dalam Hubunganmu?',
    painPoint: 'Hubungan yang sehat membutuhkan keseimbangan kekuasaan — bukan satu pihak selalu mengalah.',
    description: 'Mengukur persepsi dan penggunaan kekuasaan (power) dalam hubungan interpersonal menggunakan IPI (Interpersonal Power Inventory). Identifikasi pola pengambilan keputusan dan keseimbangan dalam relasi.',
    icon: Handshake,
    category: 'relationship',
    canDoWithPartner: true,
    subIssues: [
      { id: 'decision-making-power', label: 'Decision Making Power', shortDesc: 'Dominasi dalam pengambilan keputusan bersama' },
      { id: 'assertiveness', label: 'Assertiveness', shortDesc: 'Kemampuan menyatakan kebutuhan tanpa agresif' },
      { id: 'dependence-independence', label: 'Dependence vs Independence', shortDesc: 'Kebergantungan atau kemandirian dalam hubungan' },
      { id: 'power-balance', label: 'Power Balance', shortDesc: 'Keseimbangan kekuasaan dalam hubungan' },
    ],
    pricing: STANDARD_RELATIONSHIP_PRICING,
    users: '3k+',
    duration: '20-35 Menit',
  },
  {
    id: 'rel-orientasi-jangka-panjang',
    slug: 'orientasi-jangka-panjang-pendek',
    title: 'Orientasi Jangka Panjang vs Pendek',
    subtitle: 'Kamu Hidup untuk Hari Ini atau Masa Depan?',
    painPoint: 'Perbedaan orientasi waktu bisa membuat satu pihak merasa pasangannya tidak serius atau terlalu kaku.',
    description: 'Mengukur orientasi waktu seseorang menggunakan Time Perspective Inventory (Zimbardo). Pahami apakah kamu dan pasangan memandang masa lalu, masa kini, dan masa depan dengan cara yang sama.',
    icon: Clock,
    category: 'relationship',
    canDoWithPartner: true,
    subIssues: [
      { id: 'past-positive', label: 'Past Positive', shortDesc: 'Pandangan hangat dan nostalgia terhadap masa lalu' },
      { id: 'past-negative', label: 'Past Negative', shortDesc: 'Fokus pada pengalaman negatif masa lalu' },
      { id: 'present-hedonistic', label: 'Present Hedonistic', shortDesc: 'Orientasi menikmati hidup saat ini' },
      { id: 'present-fatalistic', label: 'Present Fatalistic', shortDesc: 'Perasaan tidak berdaya terhadap takdir' },
      { id: 'future', label: 'Future', shortDesc: 'Orientasi perencanaan dan tujuan jangka panjang' },
    ],
    pricing: STANDARD_RELATIONSHIP_PRICING,
    users: '4k+',
    duration: '20-30 Menit',
  },
]
