export { PlatformHero } from './platform-hero'
export { PhilosophySection } from './philosophy-section'
export { CurriculumPyramid } from './curriculum-pyramid'
export { ServiceGrid } from './service-grid'
export { PromoBanner } from './promo-banner'
export { PlatformNavbar } from './platform-navbar'
export { PlatformFooter } from './platform-footer'
